-- 실시간 축제 민원 관제 AI Agent — Supabase(Postgres) 스키마
--
-- 적용: Supabase 대시보드 > SQL Editor 에 통째로 붙여 넣고 Run.
--       몇 번 실행해도 안전하다.
--
-- core/db.py 의 SQLite 스키마와 같은 구조다. 시각은 ISO 문자열(TEXT)로 둔다.
-- 에이전트 코드가 문자열 비교로 창을 자르기 때문에 두 백엔드가 같게 동작한다.
--
-- 권한 원칙
--   워커(Python)   : service 연결(SUPABASE_DB_URL) — RLS 를 거치지 않는다.
--   웹(anon 키)    : 화면에 필요한 테이블 읽기만. 쓰기는 아래 RPC 3개로만.
--                    feedback 에 직접 쓰지 못한다 → 원문은 워커가 마스킹 후 넣는다.

-- ── 테이블 ─────────────────────────────────────────────────────────

create table if not exists festival (
  id bigint generated by default as identity primary key,
  name text, region text, start_date text, end_date text
);

create table if not exists zone (
  id bigint generated by default as identity primary key,
  festival_id bigint, name text unique
);

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  zone_id bigint,   -- NULL = 구역 미상 (외래키 없음)
  source text,            -- qr | replay | staff | cli
  raw_text text,          -- 마스킹된 본문
  posted_at text,
  ingested_at text,
  hash text unique
);

create table if not exists classification (
  feedback_id bigint primary key references feedback(id) on delete cascade,
  label text,
  sentiment double precision,
  is_safety integer,
  confidence double precision,
  status text default 'pending',   -- pending | done | review(운영자 확인, 유형 없음) | dismissed(유형 없음으로 닫음) | failed
  processed_at text,
  agent_note text
);
-- 확인 필요 처리 (D5-32): 모델 제안은 열로 저장, 운영자 처리 기록
alter table classification add column if not exists suggested_label text;
alter table classification add column if not exists reviewed_at text;
alter table classification add column if not exists review_action text;   -- label | dismissed
alter table classification add column if not exists decided_by text;       -- 'operator' = 운영자가 처리 (정확도에서 제외)

create table if not exists severity (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, "window" text, as_of text,
  freq integer, avg_sentiment double precision,
  base_score double precision, safety_w double precision,
  spike_w double precision, pending_w double precision,
  score double precision, grade text, formula text
);

create table if not exists alert (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, kind text, detail text, created_at text,
  acked integer default 0
);

create table if not exists department_map (
  label text primary key, department text, contact text
);

create table if not exists action_request (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, department text, count integer,
  doc_path text, status text default 'requested',
  created_at text, closed_at text,
  doc_url text, doc_json text
);

create table if not exists agent_task (
  id bigint generated by default as identity primary key,
  agent text, payload text, state text default 'queued',
  created_at text, finished_at text
);

create table if not exists agent_log (
  id bigint generated by default as identity primary key,
  agent text, action text,
  input_summary text, output_summary text, reasoning text,
  latency_ms integer, created_at text,
  input_tokens integer default 0, output_tokens integer default 0,
  cache_read_tokens integer default 0
);
alter table agent_log add column if not exists input_tokens integer default 0;
alter table agent_log add column if not exists output_tokens integer default 0;
alter table agent_log add column if not exists cache_read_tokens integer default 0;

create table if not exists briefing (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  top_label text, text text, rationale text, created_at text
);
alter table briefing add column if not exists top_issue_key text;
alter table briefing add column if not exists issue_sig text;

-- 관제 '지금 조치할 일' 카드 한 장 = 한 행 (유형×구역). 계산 열은 워커가 매 주기 갱신하고,
-- 문장 열(title·actions·evidence_quotes)은 ④통합 에이전트가 쓴다. JSON 열은 문자열이다.
create table if not exists issue (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  issue_key text unique, active integer default 1, updated_at text,
  label text, zone_id bigint, zone_name text,            -- zone_id NULL = 구역 미상
  rank_no integer, grp text,                              -- main | more | in_progress | done
  grade text, is_safety integer default 0, type_score double precision, conc double precision,
  rec double precision, card_score double precision, formula text, freq integer, type_freq integer,
  last_at text, same_zone_others integer default 0, recurred integer default 0,
  new_since_request integer default 0,                    -- 요청서를 만든 뒤 새로 생긴 구역의 카드
  action_status text, action_request_id bigint, department text, contact text,
  signature text, latest_quotes text,                     -- 최신 민원 (매 주기 갱신)
  title text, actions text, evidence_quotes text,         -- 문구와 그 근거 (문구를 다시 쓸 때만 바뀜)
  needs_judgment integer default 0,                       -- 고위험 표현 포함 → 운영자 판단 필요
  text_source text default 'template',                    -- llm | local | template
  text_updated_at text, gen_signature text, gen_max_id bigint default 0,
  gen_at text, fail_count integer default 0
);
alter table issue add column if not exists new_since_request integer default 0;
create index if not exists idx_issue_rank on issue(active, rank_no);

-- ── 운영자 코드 (할일 D5-31) ──────────────────────────────────────────
-- 민원 지우기·되돌리기, 조치 상태 변경, 조치요청서 생성은 운영자 코드가 맞을 때만 실행된다.
-- 코드는 해시(bcrypt)로만 저장한다. 두 표 모두 RLS 를 켜고 정책을 만들지 않아 anon 이 읽지 못한다.
-- 코드 값은 여기에 적지 않는다. 설정은 SQL Editor 에서 한 번만 (이 파일에 저장하지 말 것):
--   insert into operator_secret (id, code_hash)
--   values (1, extensions.crypt('<운영자 코드>', extensions.gen_salt('bf')))
--   on conflict (id) do update set code_hash = excluded.code_hash;
-- operator_secret 이 비어 있으면 관리자 RPC 는 전부 거부된다 (열린 채로 시작하지 않는다).
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists operator_secret (
  id integer primary key check (id = 1),
  code_hash text not null
);

-- 코드를 틀린 시도. 최근 10분에 5번 넘게 틀리면 그 창 동안 맞는 코드도 거부한다.
create table if not exists admin_attempt (
  id bigint generated by default as identity primary key,
  at text
);
-- 출처 해시(접속 주소 + 하루 비밀값). 원문 IP 는 저장하지 않는다. 출처를 모를 때는 '' (전체 공용) — D5-40
alter table admin_attempt add column if not exists src text default '';

create table if not exists classify_cache (
  hash text primary key, result text
);

create table if not exists replay_state (
  id bigint primary key check (id = 1),
  csv_path text, speed double precision, sim_start text, wall_start text,
  active integer default 0, cursor integer default 0, total integer default 0
);

create table if not exists festival_info (
  content_id text primary key,
  title text, addr text, start_date text, end_date text,
  tel text, homepage text, overview text,
  mapx text, mapy text, fetched_at text
);

-- 웹 접수폼 → 워커가 마스킹 후 feedback 으로 옮기고 text 를 지운다.
create table if not exists feedback_inbox (
  id bigint generated by default as identity primary key,
  zone_id bigint, text text, created_at text,
  feedback_id bigint
);

-- 웹 '조치요청서 생성' 버튼 → 워커가 처리한다.
create table if not exists doc_job (
  id bigint generated by default as identity primary key,
  label text,
  status text default 'queued',     -- queued | running | done | failed
  action_request_id bigint, error text,
  created_at text, finished_at text
);

create index if not exists idx_cls_status on classification(status);
create index if not exists idx_fb_ingested on feedback(ingested_at);
alter table feedback add column if not exists deleted_at text;   -- NULL = 살아 있음, 값 = 운영자가 지움(숨김)
create index if not exists idx_sev_asof on severity(as_of);

-- ── RLS ────────────────────────────────────────────────────────────
-- 모든 테이블 RLS 를 켠다. 정책이 없는 테이블은 anon 이 아예 못 본다.
do $$
declare t text;
begin
  foreach t in array array[
    'festival','zone','feedback','classification','severity','alert',
    'department_map','action_request','agent_task','agent_log','briefing',
    'classify_cache','replay_state','festival_info','feedback_inbox','doc_job','issue',
    'operator_secret','admin_attempt']
  loop
    execute format('alter table %I enable row level security', t);
  end loop;
end $$;

-- 화면 표시용 읽기 권한
do $$
declare t text;
begin
  foreach t in array array[
    'festival','zone','feedback','classification','severity','alert',
    'action_request','briefing','doc_job','issue']
  loop
    execute format('drop policy if exists anon_read on %I', t);
    execute format('create policy anon_read on %I for select to anon, authenticated using (true)', t);
  end loop;
end $$;

-- ── RPC (웹에서 쓰기는 이것만) ─────────────────────────────────────

-- 민원 접수. 접수번호(inbox id)를 돌려준다.
create or replace function submit_feedback(p_zone_id bigint, p_text text)
returns bigint
language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  -- 한글·영문·숫자가 2개 이상이어야 한다 ('...' 'ㅋㅋ' '!!!!' 거부). core/privacy.has_content 와 같은 규칙
  if p_text is null or length(regexp_replace(p_text, '[^가-힣A-Za-z0-9]', '', 'g')) < 2 then
    raise exception '어떤 불편인지 조금 더 적어 주세요';
  end if;
  if length(p_text) > 500 then
    raise exception '500자 이내로 적어 주세요';
  end if;
  if not exists (select 1 from zone where id = p_zone_id) then
    raise exception '구역을 선택해 주세요';
  end if;
  insert into feedback_inbox (zone_id, text, created_at)
  values (p_zone_id, btrim(p_text), to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'))
  returning id into v_id;
  return v_id;
end $$;

-- ── 관리자 RPC (운영자 코드 p_code 필요) ──────────────────────────────
-- 코드가 틀렸을 때 예외(raise)를 던지면 그 트랜잭션이 롤백돼 '틀린 시도' 기록도 사라진다.
-- 그래서 코드 검사 결과는 예외가 아니라 반환값으로 준다: {"ok": true, ...} / {"ok": false, "error": "…"}.
-- (없는 민원·잘못된 상태 같은 검증 오류는 코드를 통과한 뒤의 일이라 예외 그대로다.)
-- 예전 시그니처(코드 인자 없음)는 지운다 — 남겨 두면 anon 이 코드 없이 그대로 호출할 수 있다.
drop function if exists request_doc(text);
drop function if exists set_action_status(bigint, text);
drop function if exists delete_feedback(bigint);
drop function if exists restore_feedback(bigint);

-- 코드 검사 (내부용). 통과하면 null, 아니면 거부 사유를 돌려준다. anon 이 직접 부를 수 없다.
create or replace function admin_gate(p_code text)
returns text
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_hash text;
  v_fails integer;
  v_ip text;
  v_src text := '';
begin
  select code_hash into v_hash from operator_secret where id = 1;
  if v_hash is null then
    return '운영자 코드가 필요합니다';            -- 코드를 안 정했으면 전부 거부
  end if;
  -- 출처별 실패 횟수 (D5-40). PostgREST 가 넘겨 주는 x-forwarded-for 의 첫 값을 '오늘 날짜 + 코드 해시'를 키로 해시한다.
  -- [확인 필요] Supabase 적용 시 이 헤더가 실제로 오는지 확인. 안 오면 v_src 는 '' — 예전처럼 전체가 한 출처로 묶인다.
  begin
    v_ip := trim(split_part(coalesce(current_setting('request.headers', true)::json->>'x-forwarded-for', ''), ',', 1));
  exception when others then
    v_ip := '';
  end;
  if v_ip <> '' then
    v_src := left(encode(hmac(v_ip, v_hash || to_char(current_date, 'YYYY-MM-DD'), 'sha256'), 'hex'), 16);
  end if;
  delete from admin_attempt                                                   -- 실패 기록은 24시간 뒤 삭제
   where at < to_char((now() - interval '24 hours') at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
  select count(*) into v_fails from admin_attempt
   where coalesce(src, '') = v_src
     and at >= to_char((now() - interval '10 minutes') at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
  if v_fails >= 5 then
    return '시도가 너무 많습니다. 10분 뒤에 다시 시도하세요';   -- 잠금 중에는 맞는 코드도 거부
  end if;
  if p_code is null or p_code = '' then
    return '운영자 코드가 필요합니다';            -- 코드를 안 보낸 요청은 실패로 세지 않는다
  end if;
  if crypt(p_code, v_hash) = v_hash then
    delete from admin_attempt where coalesce(src, '') = v_src;   -- 맞으면 이 출처의 실패 기록만 비운다
    return null;
  end if;
  insert into admin_attempt (at, src)
  values (to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'), v_src);
  return '운영자 코드가 필요합니다';
end $$;

-- 코드가 맞는지만 확인 (코드 입력 창용)
create or replace function check_admin(p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  return jsonb_build_object('ok', true);
end $$;

-- 조치요청서 생성 요청. 같은 유형이 이미 대기 중이면 그 요청 id 를 돌려준다.
create or replace function request_doc(p_label text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_id bigint;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if not exists (select 1 from department_map where label = p_label) then
    raise exception '모르는 민원 유형입니다: %', p_label;
  end if;
  select id into v_id from doc_job
   where label = p_label and status in ('queued', 'running') limit 1;
  if v_id is null then
    insert into doc_job (label, created_at)
    values (p_label, to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'))
    returning id into v_id;
  end if;
  return jsonb_build_object('ok', true, 'id', v_id);
end $$;

-- 조치 상태 변경 (요청 → 조치중 → 완료)
create or replace function set_action_status(p_id bigint, p_status text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if p_status not in ('requested', 'in_progress', 'done') then
    raise exception '잘못된 상태: %', p_status;
  end if;
  update action_request
     set status = p_status,
         closed_at = case when p_status = 'done'
                          then to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
                          else null end
   where id = p_id;
  return jsonb_build_object('ok', true);
end $$;

-- 민원 숨김·되돌리기 (관제 '민원 지우기'). 행은 지우지 않고 deleted_at 만 바꾼다.
-- 건수·심각도·알림·브리핑·인용·카드는 deleted_at IS NULL 인 민원만 센다.
create or replace function delete_feedback(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  update feedback
     set deleted_at = to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
   where id = p_id;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function restore_feedback(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  update feedback set deleted_at = null where id = p_id;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  return jsonb_build_object('ok', true);
end $$;

-- ── 확인 필요(review) 처리 (D5-32) — 운영자 코드 필요, 상태 조건을 건다 ──────────
-- 유형 지정: status='review' → 'done'. 안전·혼잡이면 안전 의심 자동, 긍정은 안전 아님, 그 밖엔 p_is_safety(없으면 모델 값).
-- 같은 문장이 다시 오면 쓰도록 classify_cache 에도 넣는다 (Python 의 sha256(raw_text) 와 같은 해시).
create or replace function resolve_review(p_id bigint, p_label text, p_is_safety boolean, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
  v_raw text;
  v_safe integer;
  v_now text := to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if p_label not in ('parking', 'restroom', 'price', 'guide', 'crowd', 'safety', 'positive') then
    raise exception '모르는 민원 유형입니다: %', p_label;
  end if;
  select * into v_row from classification where feedback_id = p_id for update;   -- 두 운영자가 동시에 눌러도 한 번만
  if not found then
    raise exception '없는 민원입니다';
  end if;
  if v_row.status <> 'review' then
    raise exception '이미 처리된 민원입니다';
  end if;
  v_safe := case when p_label in ('safety', 'crowd') then 1
                 when p_label = 'positive' then 0
                 when p_is_safety is null then coalesce(v_row.is_safety, 0)
                 when p_is_safety then 1 else 0 end;
  update classification
     set label = p_label, is_safety = v_safe, confidence = 1.0, status = 'done',
         agent_note = '운영자 지정 (모델 제안: ' || coalesce(v_row.suggested_label, '-') || ')',
         reviewed_at = v_now, review_action = 'label', decided_by = 'operator'
   where feedback_id = p_id;
  select raw_text into v_raw from feedback where id = p_id;
  insert into classify_cache (hash, result)
  values (encode(digest(v_raw, 'sha256'), 'hex'),
          json_build_object('label', p_label, 'sentiment', coalesce(v_row.sentiment, -0.5),
                            'is_safety', v_safe = 1, 'confidence', 1.0)::text)
  on conflict (hash) do update set result = excluded.result;
  return jsonb_build_object('ok', true);
end $$;

-- 유형 없음으로 닫기: 'review' → 'dismissed'. 진짜 방문객 의견이지만 유형을 붙일 수 없는 것.
create or replace function dismiss_review(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  select * into v_row from classification where feedback_id = p_id for update;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  if v_row.status <> 'review' then
    raise exception '이미 처리된 민원입니다';
  end if;
  update classification
     set status = 'dismissed', review_action = 'dismissed', decided_by = 'operator',
         reviewed_at = to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
   where feedback_id = p_id;
  return jsonb_build_object('ok', true);
end $$;

-- 되돌리기: 닫은 것(dismissed)이나 운영자가 지정한 것(done + decided_by='operator')을 다시 'review' 로.
create or replace function reopen_review(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
  v_raw text;
  v_was_label boolean;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  select * into v_row from classification where feedback_id = p_id for update;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  v_was_label := v_row.status = 'done' and v_row.decided_by = 'operator';
  if not (v_row.status = 'dismissed' or v_was_label) then
    raise exception '되돌릴 수 있는 처리가 아닙니다';
  end if;
  update classification
     set status = 'review', label = null, confidence = null,
         agent_note = '확인 필요 — 운영자가 되돌림. 모델 제안: ' || coalesce(v_row.suggested_label, '-'),
         reviewed_at = null, review_action = null, decided_by = null
   where feedback_id = p_id;
  if v_was_label then                                  -- 지정하며 넣어 둔 같은 문장 캐시는 지운다
    select raw_text into v_raw from feedback where id = p_id;
    delete from classify_cache where hash = encode(digest(v_raw, 'sha256'), 'hex');
  end if;
  return jsonb_build_object('ok', true);
end $$;

revoke all on function submit_feedback(bigint, text) from public;
revoke all on function admin_gate(text) from public, anon, authenticated;
revoke all on function check_admin(text) from public;
revoke all on function request_doc(text, text) from public;
revoke all on function set_action_status(bigint, text, text) from public;
revoke all on function delete_feedback(bigint, text) from public;
revoke all on function restore_feedback(bigint, text) from public;
revoke all on function resolve_review(bigint, text, boolean, text) from public;
revoke all on function dismiss_review(bigint, text) from public;
revoke all on function reopen_review(bigint, text) from public;
-- 방문객(anon)이 코드 없이 쓸 수 있는 것은 접수 하나뿐. 나머지는 실행은 열어 두되 코드가 맞아야 동작한다.
grant execute on function submit_feedback(bigint, text) to anon, authenticated;
grant execute on function check_admin(text) to anon, authenticated;
grant execute on function request_doc(text, text) to anon, authenticated;
grant execute on function set_action_status(bigint, text, text) to anon, authenticated;
grant execute on function delete_feedback(bigint, text) to anon, authenticated;
grant execute on function restore_feedback(bigint, text) to anon, authenticated;
grant execute on function resolve_review(bigint, text, boolean, text) to anon, authenticated;
grant execute on function dismiss_review(bigint, text) to anon, authenticated;
grant execute on function reopen_review(bigint, text) to anon, authenticated;

-- ── Realtime ───────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'feedback','classification','severity','alert','action_request','briefing','doc_job','issue']
  loop
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;

-- ── Storage: 조치요청서 DOCX ───────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('docs', 'docs', true)
on conflict (id) do nothing;
