-- 실시간 축제 민원 관제 AI Agent — Supabase(Postgres) 스키마
--
-- 적용: Supabase 대시보드 > SQL Editor 에 통째로 붙여 넣고 Run.
--       몇 번 실행해도 안전하다.
--
-- core/db.py 의 SQLite 스키마와 같은 구조다. 시각은 ISO 문자열(TEXT)로 둔다.
-- 에이전트 코드가 문자열 비교로 창을 자르기 때문에 두 백엔드가 같게 동작한다.
--
-- 권한 원칙
--   워커(Python)   : service 연결(SUPABASE_DB_URL) — RLS 를 거치지 않는다.
--   웹(anon 키)    : 화면에 필요한 테이블 읽기만. 쓰기는 아래 RPC 3개로만.
--                    feedback 에 직접 쓰지 못한다 → 원문은 워커가 마스킹 후 넣는다.

-- ── 테이블 ─────────────────────────────────────────────────────────

create table if not exists festival (
  id bigint generated by default as identity primary key,
  name text, region text, start_date text, end_date text
);

create table if not exists zone (
  id bigint generated by default as identity primary key,
  festival_id bigint, name text unique
);

-- 운영자 설정 (D5-90): 구역 숨김 — 민원이 달려 있어 지우지 않고 방문객 구역 선택에서만 뺀다.
alter table zone add column if not exists hidden integer default 0;

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  zone_id bigint,   -- NULL = 구역 미상 (외래키 없음)
  source text,            -- qr | replay | staff | cli
  raw_text text,          -- 마스킹된 본문
  posted_at text,
  ingested_at text,
  hash text unique
);

create table if not exists classification (
  feedback_id bigint primary key references feedback(id) on delete cascade,
  label text,
  sentiment double precision,
  is_safety integer,
  confidence double precision,
  status text default 'pending',   -- pending | done | review(운영자 확인, 유형 없음) | dismissed(유형 없음으로 닫음) | failed
  processed_at text,
  agent_note text
);
-- 확인 필요 처리 (D5-32): 모델 제안은 열로 저장, 운영자 처리 기록
alter table classification add column if not exists suggested_label text;
alter table classification add column if not exists reviewed_at text;
alter table classification add column if not exists review_action text;   -- label | dismissed
alter table classification add column if not exists decided_by text;       -- 'operator' = 운영자가 처리 (정확도에서 제외)

create table if not exists severity (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, "window" text, as_of text,
  freq integer, avg_sentiment double precision,
  base_score double precision, safety_w double precision,
  spike_w double precision, pending_w double precision,
  score double precision, grade text, formula text
);

create table if not exists alert (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, kind text, detail text, created_at text,
  acked integer default 0
);

create table if not exists department_map (
  label text primary key, department text, contact text
);

create table if not exists action_request (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  label text, department text, count integer,
  doc_path text, status text default 'requested',
  created_at text, closed_at text,
  doc_url text, doc_json text
);

create table if not exists agent_task (
  id bigint generated by default as identity primary key,
  agent text, payload text, state text default 'queued',
  created_at text, finished_at text
);

create table if not exists agent_log (
  id bigint generated by default as identity primary key,
  agent text, action text,
  input_summary text, output_summary text, reasoning text,
  latency_ms integer, created_at text,
  input_tokens integer default 0, output_tokens integer default 0,
  cache_read_tokens integer default 0
);
alter table agent_log add column if not exists input_tokens integer default 0;
alter table agent_log add column if not exists output_tokens integer default 0;
alter table agent_log add column if not exists cache_read_tokens integer default 0;

create table if not exists briefing (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  top_label text, text text, rationale text, created_at text
);
alter table briefing add column if not exists top_issue_key text;
alter table briefing add column if not exists issue_sig text;

-- 관제 '지금 조치할 일' 카드 한 장 = 한 행 (유형×구역). 계산 열은 워커가 매 주기 갱신하고,
-- 문장 열(title·actions·evidence_quotes)은 ④통합 에이전트가 쓴다. JSON 열은 문자열이다.
create table if not exists issue (
  id bigint generated by default as identity primary key,
  festival_id bigint,
  issue_key text unique, active integer default 1, updated_at text,
  label text, zone_id bigint, zone_name text,            -- zone_id NULL = 구역 미상
  rank_no integer, grp text,                              -- main | more | in_progress | done
  grade text, is_safety integer default 0, type_score double precision, conc double precision,
  rec double precision, card_score double precision, formula text, freq integer, type_freq integer,
  last_at text, same_zone_others integer default 0, recurred integer default 0,
  new_since_request integer default 0,                    -- 요청서를 만든 뒤 새로 생긴 구역의 카드
  action_status text, action_request_id bigint, department text, contact text,
  signature text, latest_quotes text,                     -- 최신 민원 (매 주기 갱신)
  title text, actions text, evidence_quotes text,         -- 문구와 그 근거 (문구를 다시 쓸 때만 바뀜)
  needs_judgment integer default 0,                       -- 고위험 표현 포함 → 운영자 판단 필요
  text_source text default 'template',                    -- llm | local | template
  text_updated_at text, gen_signature text, gen_max_id bigint default 0,
  gen_at text, fail_count integer default 0
);
alter table issue add column if not exists new_since_request integer default 0;
create index if not exists idx_issue_rank on issue(active, rank_no);

-- ── 운영자 코드 (할일 D5-31) ──────────────────────────────────────────
-- 민원 지우기·되돌리기, 조치 상태 변경, 조치요청서 생성은 운영자 코드가 맞을 때만 실행된다.
-- 코드는 해시(bcrypt)로만 저장한다. 두 표 모두 RLS 를 켜고 정책을 만들지 않아 anon 이 읽지 못한다.
-- 코드 값은 여기에 적지 않는다. 설정은 SQL Editor 에서 한 번만 (이 파일에 저장하지 말 것):
--   insert into operator_secret (id, code_hash)
--   values (1, extensions.crypt('<운영자 코드>', extensions.gen_salt('bf')))
--   on conflict (id) do update set code_hash = excluded.code_hash;
-- operator_secret 이 비어 있으면 관리자 RPC 는 전부 거부된다 (열린 채로 시작하지 않는다).
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists operator_secret (
  id integer primary key check (id = 1),
  code_hash text not null
);

-- 코드를 틀린 시도. 최근 10분에 5번 넘게 틀리면 그 창 동안 맞는 코드도 거부한다.
create table if not exists admin_attempt (
  id bigint generated by default as identity primary key,
  at text
);
-- 출처 해시(접속 주소 + 하루 비밀값). 원문 IP 는 저장하지 않는다. 출처를 모를 때는 '' (전체 공용) — D5-40
alter table admin_attempt add column if not exists src text default '';

create table if not exists classify_cache (
  hash text primary key, result text
);

-- 개발자 보기 (D5-62): 워커 루프 상태 한 줄씩 (name = ingest|classify|doc_jobs|agents|issues, '_backend' 는 LLM 백엔드를 note 에).
-- 방문객이 못 읽게 RLS 를 켜고 정책은 만들지 않는다. dev_feed(p_code, ...) 만 (운영자 코드) 읽는다.
create table if not exists worker_status (
  name text primary key, last_at text, took_ms integer, ok integer default 1, note text
);
alter table severity add column if not exists spike_mult double precision;   -- 급증 배수 (내부값)
alter table severity add column if not exists safety_freq integer;           -- 안전(is_safety) 민원 수 (내부값)

create table if not exists replay_state (
  id bigint primary key check (id = 1),
  csv_path text, speed double precision, sim_start text, wall_start text,
  active integer default 0, cursor integer default 0, total integer default 0
);

create table if not exists festival_info (
  content_id text primary key,
  title text, addr text, start_date text, end_date text,
  tel text, homepage text, overview text,
  mapx text, mapy text, fetched_at text
);

-- 웹 접수폼 → 워커가 마스킹 후 feedback 으로 옮기고 text 를 지운다.
create table if not exists feedback_inbox (
  id bigint generated by default as identity primary key,
  zone_id bigint, text text, created_at text,
  feedback_id bigint
);
alter table feedback_inbox add column if not exists dup_count integer default 0;   -- 합쳐진 횟수 (D5-33 ①)

-- 출처별 폭주 제한 (D5-33 ②). 출처 = 접속 주소의 하루짜리 해시(원문 IP 아님). 24시간 뒤 삭제. 민원 행과 연결하지 않는다.
create table if not exists submit_rate (
  id bigint generated by default as identity primary key,
  src text, at text
);
create index if not exists idx_rate_src_at on submit_rate(src, at);

-- 접수가 들어오면 워커를 바로 깨운다 (D5-71): feedback_inbox 에 행이 생길 때마다 pg_notify. 워커는 LISTEN 으로 받고, 놓쳐도 폴링이 예비로 받는다.
-- 수거 쿼리(feedback_id is null 인 접수 찾기)가 비어 있을 때 가볍도록 아직 안 옮긴 접수만 색인한다.
create or replace function notify_inbox()
returns trigger
language plpgsql as $$
begin
  perform pg_notify('feedback_inbox', new.id::text);
  return new;
end $$;
revoke all on function notify_inbox() from public, anon, authenticated;

-- 웹 '조치요청서 생성' 버튼 → 워커가 처리한다.
create table if not exists doc_job (
  id bigint generated by default as identity primary key,
  label text,
  status text default 'queued',     -- queued | running | done | failed
  action_request_id bigint, error text,
  created_at text, finished_at text
);

drop trigger if exists trg_notify_inbox on feedback_inbox;
create trigger trg_notify_inbox after insert on feedback_inbox
  for each row execute function notify_inbox();
create index if not exists idx_inbox_pending on feedback_inbox(id) where feedback_id is null;

create index if not exists idx_cls_status on classification(status);
create index if not exists idx_fb_ingested on feedback(ingested_at);
alter table feedback add column if not exists deleted_at text;   -- NULL = 살아 있음, 값 = 운영자가 지움(숨김)
alter table feedback add column if not exists dup_count integer default 0;
-- 조회 속도 (D5-37)
create index if not exists idx_fb_posted on feedback(posted_at);
create index if not exists idx_fb_src_posted on feedback(source, posted_at);
create index if not exists idx_fb_deleted on feedback(deleted_at);   -- 같은 글을 2분 안에 또 보내 합쳐진 횟수 (D5-33 ①)
create index if not exists idx_sev_asof on severity(as_of);

-- ── RLS ────────────────────────────────────────────────────────────
-- 모든 테이블 RLS 를 켠다. 정책이 없는 테이블은 anon 이 아예 못 본다.
do $$
declare t text;
begin
  foreach t in array array[
    'festival','zone','feedback','classification','severity','alert',
    'department_map','action_request','agent_task','agent_log','briefing',
    'classify_cache','replay_state','festival_info','feedback_inbox','doc_job','issue',
    'operator_secret','admin_attempt','submit_rate','worker_status']
  loop
    execute format('alter table %I enable row level security', t);
  end loop;
end $$;

-- 화면 표시용 읽기 권한
do $$
declare t text;
begin
  foreach t in array array[
    'festival','zone','feedback','classification','severity','alert',
    'action_request','briefing','doc_job','issue']
  loop
    execute format('drop policy if exists anon_read on %I', t);
    execute format('create policy anon_read on %I for select to anon, authenticated using (true)', t);
  end loop;
end $$;

-- ── RPC (웹에서 쓰기는 이것만) ─────────────────────────────────────

-- 민원 접수. 접수번호(inbox id)를 돌려준다.
create or replace function submit_feedback(p_zone_id bigint, p_text text)
returns bigint
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_id bigint;
  v_src text;
  v_norm text;
  v_cut text;
  v_now timestamp := now() at time zone 'Asia/Seoul';
  -- D5-33 설계값 [확인 필요: 리허설로 조정]. 끄려면 false 로.
  v_dedup_on constant boolean := true;
  -- ②출처별 제한은 **기본 꺼짐**. x-forwarded-for 맨 오른쪽 값이 게이트웨이 주소면 모두가 한 출처로 묶여 정상 신고가 막힌다.
  -- [확인 필요] Supabase 에서 헤더가 실제 접속자 주소인지 확인한 뒤에만 true 로 켠다.
  v_limit_on constant boolean := false;
begin
  -- 한글·영문·숫자가 2개 이상이어야 한다 ('...' 'ㅋㅋ' '!!!!' 거부). core/privacy.has_content 와 같은 규칙
  if p_text is null or length(regexp_replace(p_text, '[^가-힣A-Za-z0-9]', '', 'g')) < 2 then
    raise exception '어떤 불편인지 조금 더 적어 주세요';
  end if;
  if length(p_text) > 500 then
    raise exception '500자 이내로 적어 주세요';
  end if;
  if not exists (select 1 from zone where id = p_zone_id) then
    raise exception '구역을 선택해 주세요';
  end if;
  -- ② 출처별 폭주 제한: 1분 10건 · 10분 30건. 출처를 모르면(헤더 없음) 건너뛴다. 기록은 24시간 뒤 삭제.
  v_src := request_source();
  if v_limit_on and v_src <> '' then
    delete from submit_rate where at < to_char(v_now - interval '24 hours', 'YYYY-MM-DD"T"HH24:MI:SS');
    if (select count(*) from submit_rate where src = v_src
         and at >= to_char(v_now - interval '60 seconds', 'YYYY-MM-DD"T"HH24:MI:SS')) >= 10
       or (select count(*) from submit_rate where src = v_src
            and at >= to_char(v_now - interval '600 seconds', 'YYYY-MM-DD"T"HH24:MI:SS')) >= 30 then
      raise exception '잠시 후 다시 보내 주세요';
    end if;
    insert into submit_rate (src, at) values (v_src, to_char(v_now, 'YYYY-MM-DD"T"HH24:MI:SS'));
  end if;
  -- ① 같은 글 합치기: 같은 구역 + 공백·기호를 지운 같은 본문이 2분 안에 있으면 새로 넣지 않고 같은 접수번호를 돌려준다.
  -- (워커가 옮긴 뒤에는 마스킹본과 비교하므로 개인정보가 섞인 글은 합쳐지지 않을 수 있다 — [확인 필요])
  if v_dedup_on then
    v_norm := lower(regexp_replace(p_text, '[^가-힣A-Za-z0-9]', '', 'g'));
    -- 같은 구역·같은 글이 거의 동시에 두 번 와도 한 건이 되게, 이 트랜잭션이 끝날 때까지 같은 글끼리는 줄을 세운다
    perform pg_advisory_xact_lock(hashtext(p_zone_id::text || ':' || v_norm));
    v_cut := to_char(v_now - interval '120 seconds', 'YYYY-MM-DD"T"HH24:MI:SS');
    select id into v_id from feedback_inbox
     where zone_id = p_zone_id and text is not null and created_at >= v_cut
       and lower(regexp_replace(text, '[^가-힣A-Za-z0-9]', '', 'g')) = v_norm
     order by id desc limit 1;
    if found then
      update feedback_inbox set dup_count = coalesce(dup_count, 0) + 1 where id = v_id;
      return v_id;
    end if;
    select id into v_id from feedback
     where zone_id = p_zone_id and deleted_at is null and ingested_at >= v_cut
       and lower(regexp_replace(raw_text, '[^가-힣A-Za-z0-9]', '', 'g')) = v_norm
     order by id desc limit 1;
    if found then
      update feedback set dup_count = coalesce(dup_count, 0) + 1 where id = v_id;
      return coalesce((select max(id) from feedback_inbox where feedback_id = v_id), v_id);
    end if;
  end if;
  insert into feedback_inbox (zone_id, text, created_at)
  values (p_zone_id, btrim(p_text), to_char(v_now, 'YYYY-MM-DD"T"HH24:MI:SS'))
  returning id into v_id;
  return v_id;
end $$;

-- ── 관리자 RPC (운영자 코드 p_code 필요) ──────────────────────────────
-- 코드가 틀렸을 때 예외(raise)를 던지면 그 트랜잭션이 롤백돼 '틀린 시도' 기록도 사라진다.
-- 그래서 코드 검사 결과는 예외가 아니라 반환값으로 준다: {"ok": true, ...} / {"ok": false, "error": "…"}.
-- (없는 민원·잘못된 상태 같은 검증 오류는 코드를 통과한 뒤의 일이라 예외 그대로다.)
-- 예전 시그니처(코드 인자 없음)는 지운다 — 남겨 두면 anon 이 코드 없이 그대로 호출할 수 있다.
drop function if exists request_doc(text);
drop function if exists set_action_status(bigint, text);
drop function if exists delete_feedback(bigint);
drop function if exists restore_feedback(bigint);

-- 요청한 쪽의 '출처' 해시 (내부용, D5-40·D5-33). PostgREST 가 넘겨 주는 x-forwarded-for 의 **맨 오른쪽** 값을
-- '오늘 날짜 + 코드 해시'를 키로 HMAC 해서 앞 16자만 쓴다. 원문 IP 는 저장하지 않는다. 헤더가 없으면 '' (출처를 모름).
-- 맨 오른쪽만 쓰는 이유(D5-43): 게이트웨이가 마지막에 덧붙인 값이고, 왼쪽은 접속한 쪽이 직접 넣어 보낸 것일 수 있다.
-- [확인 필요] Supabase 적용 시 ①이 헤더가 실제로 오는지 ②맨 오른쪽이 게이트웨이가 붙인 접속자 주소인지(앞에 프록시가 더 있으면
-- 오른쪽에서 n번째) 확인. 안 오면 '' — 운영자 코드 잠금은 전체 공용, 출처별 폭주 제한(②)은 건너뛴다.
create or replace function request_source()
returns text
language plpgsql stable security definer set search_path = public, extensions as $$
declare
  v_hdr text;
  v_parts text[];
  v_ip text;
  v_key text;
begin
  begin
    v_hdr := coalesce(current_setting('request.headers', true)::json->>'x-forwarded-for', '');
  exception when others then
    v_hdr := '';
  end;
  v_parts := string_to_array(v_hdr, ',');
  v_ip := trim(coalesce(v_parts[greatest(coalesce(array_length(v_parts, 1), 1), 1)], ''));
  if v_ip = '' then
    return '';
  end if;
  select code_hash into v_key from operator_secret where id = 1;
  if v_key is null then
    return '';                                   -- 비밀값이 없으면 출처를 구분하지 않는다 (고정 문자열 키는 쓰지 않는다)
  end if;
  return left(encode(hmac(v_ip, v_key || to_char(current_date, 'YYYY-MM-DD'), 'sha256'), 'hex'), 16);
end $$;

-- 코드 검사 (내부용). 통과하면 null, 아니면 거부 사유를 돌려준다. anon 이 직접 부를 수 없다.
create or replace function admin_gate(p_code text)
returns text
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_hash text;
  v_fails integer;
  v_src text := '';
begin
  select code_hash into v_hash from operator_secret where id = 1;
  if v_hash is null then
    return '운영자 코드가 필요합니다';            -- 코드를 안 정했으면 전부 거부
  end if;
  v_src := request_source();            -- 출처별 실패 횟수 (D5-40) — 해시 규칙은 request_source() 참고
  delete from admin_attempt                                                   -- 실패 기록은 24시간 뒤 삭제
   where at < to_char((now() - interval '24 hours') at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
  select count(*) into v_fails from admin_attempt
   where coalesce(src, '') = v_src
     and at >= to_char((now() - interval '10 minutes') at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
  if v_fails >= 5 then
    return '시도가 너무 많습니다. 10분 뒤에 다시 시도하세요';   -- 잠금 중에는 맞는 코드도 거부
  end if;
  if p_code is null or p_code = '' then
    return '운영자 코드가 필요합니다';            -- 코드를 안 보낸 요청은 실패로 세지 않는다
  end if;
  if crypt(p_code, v_hash) = v_hash then
    delete from admin_attempt where coalesce(src, '') = v_src;   -- 맞으면 이 출처의 실패 기록만 비운다
    return null;
  end if;
  insert into admin_attempt (at, src)
  values (to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'), v_src);
  return '운영자 코드가 필요합니다';
end $$;

-- 코드가 맞는지만 확인 (코드 입력 창용)
create or replace function check_admin(p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  return jsonb_build_object('ok', true);
end $$;

-- 조치요청서 생성 요청. 같은 유형이 이미 대기 중이면 그 요청 id 를 돌려준다.
create or replace function request_doc(p_label text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_id bigint;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if not exists (select 1 from department_map where label = p_label) then
    raise exception '모르는 민원 유형입니다: %', p_label;
  end if;
  select id into v_id from doc_job
   where label = p_label and status in ('queued', 'running') limit 1;
  if v_id is null then
    insert into doc_job (label, created_at)
    values (p_label, to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'))
    returning id into v_id;
  end if;
  return jsonb_build_object('ok', true, 'id', v_id);
end $$;

-- 조치 상태 변경 (요청 → 조치중 → 완료)
create or replace function set_action_status(p_id bigint, p_status text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if p_status not in ('requested', 'in_progress', 'done') then
    raise exception '잘못된 상태: %', p_status;
  end if;
  update action_request
     set status = p_status,
         closed_at = case when p_status = 'done'
                          then to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
                          else null end
   where id = p_id;
  return jsonb_build_object('ok', true);
end $$;

-- 민원 숨김·되돌리기 (관제 '민원 지우기'). 행은 지우지 않고 deleted_at 만 바꾼다.
-- 건수·심각도·알림·브리핑·인용·카드는 deleted_at IS NULL 인 민원만 센다.
create or replace function delete_feedback(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  update feedback
     set deleted_at = to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
   where id = p_id;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function restore_feedback(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  update feedback set deleted_at = null where id = p_id;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  return jsonb_build_object('ok', true);
end $$;

-- 최근에 지운 민원 50건 (D5-42) — 되돌리기용 목록. 운영자 코드가 필요하다. db.list_deleted 와 같은 내용.
create or replace function list_deleted(p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_items jsonb;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  select coalesce(jsonb_agg(x order by x.deleted_at desc, x.id desc), '[]'::jsonb) into v_items
    from (select f.id, f.raw_text, coalesce(z.name, '구역 미상') as zone, f.zone_id, f.posted_at, f.deleted_at,
                 c.label, c.status
            from feedback f
            left join zone z on z.id = f.zone_id
            left join classification c on c.feedback_id = f.id
           where f.deleted_at is not null
           order by f.deleted_at desc, f.id desc
           limit 50) x;
  return jsonb_build_object('ok', true, 'items', v_items);
end $$;

-- ── 확인 필요(review) 처리 (D5-32) — 운영자 코드 필요, 상태 조건을 건다 ──────────
-- 유형 지정: status='review' → 'done'. 안전이면 안전 의심 자동, 긍정은 안전 아님, 그 밖엔(혼잡 포함, D5-59) p_is_safety(없으면 모델 값).
-- 같은 문장이 다시 오면 쓰도록 classify_cache 에도 넣는다 (Python 의 sha256(raw_text) 와 같은 해시).
create or replace function resolve_review(p_id bigint, p_label text, p_is_safety boolean, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
  v_raw text;
  v_safe integer;
  v_now text := to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  if p_label not in ('parking', 'restroom', 'price', 'guide', 'crowd', 'safety', 'positive') then
    raise exception '모르는 민원 유형입니다: %', p_label;
  end if;
  select * into v_row from classification where feedback_id = p_id for update;   -- 두 운영자가 동시에 눌러도 한 번만
  if not found then
    raise exception '없는 민원입니다';
  end if;
  if v_row.status <> 'review' then
    raise exception '이미 처리된 민원입니다';
  end if;
  v_safe := case when p_label = 'safety' then 1
                 when p_label = 'positive' then 0
                 when p_is_safety is null then coalesce(v_row.is_safety, 0)
                 when p_is_safety then 1 else 0 end;
  update classification
     set label = p_label, is_safety = v_safe, confidence = 1.0, status = 'done',
         agent_note = '운영자 지정 (모델 제안: ' || coalesce(v_row.suggested_label, '-') || ')',
         reviewed_at = v_now, review_action = 'label', decided_by = 'operator'
   where feedback_id = p_id;
  select raw_text into v_raw from feedback where id = p_id;
  insert into classify_cache (hash, result)
  values (encode(digest(v_raw, 'sha256'), 'hex'),
          json_build_object('label', p_label, 'sentiment', coalesce(v_row.sentiment, -0.5),
                            'is_safety', v_safe = 1, 'confidence', 1.0)::text)
  on conflict (hash) do update set result = excluded.result;
  return jsonb_build_object('ok', true);
end $$;

-- 유형 없음으로 닫기: 'review' → 'dismissed'. 진짜 방문객 의견이지만 유형을 붙일 수 없는 것.
create or replace function dismiss_review(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  select * into v_row from classification where feedback_id = p_id for update;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  if v_row.status <> 'review' then
    raise exception '이미 처리된 민원입니다';
  end if;
  update classification
     set status = 'dismissed', review_action = 'dismissed', decided_by = 'operator',
         reviewed_at = to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS')
   where feedback_id = p_id;
  return jsonb_build_object('ok', true);
end $$;

-- 되돌리기: 닫은 것(dismissed)이나 운영자가 지정한 것(done + decided_by='operator')을 다시 'review' 로.
create or replace function reopen_review(p_id bigint, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_err text;
  v_row classification%rowtype;
  v_raw text;
  v_was_label boolean;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then
    return jsonb_build_object('ok', false, 'error', v_err);
  end if;
  select * into v_row from classification where feedback_id = p_id for update;
  if not found then
    raise exception '없는 민원입니다';
  end if;
  v_was_label := v_row.status = 'done' and v_row.decided_by = 'operator';
  if not (v_row.status = 'dismissed' or v_was_label) then
    raise exception '되돌릴 수 있는 처리가 아닙니다';
  end if;
  update classification
     set status = 'review', label = null, confidence = null,
         agent_note = '확인 필요 — 운영자가 되돌림. 모델 제안: ' || coalesce(v_row.suggested_label, '-'),
         reviewed_at = null, review_action = null, decided_by = null
   where feedback_id = p_id;
  if v_was_label then                                  -- 지정하며 넣어 둔 같은 문장 캐시는 지운다
    select raw_text into v_raw from feedback where id = p_id;
    delete from classify_cache where hash = encode(digest(v_raw, 'sha256'), 'hex');
  end if;
  return jsonb_build_object('ok', true);
end $$;

-- ── 개발자 보기 (D5-62) — 공개 읽기 전용 (운영자 코드 없음, 심사위원이 에이전트 동작을 보는 용도) ──────────
-- 공개로 나가도 안전하게: ① 읽기만 한다(쓰는 것은 호출 빈도 기록 한 줄뿐) ② 모든 문자열은 dev_redact() 로 개인정보·경로·주소·키·해시를 가린다
-- ③ 운영자 코드·operator_secret·출처 해시(admin_attempt·submit_rate 의 원본 src)·환경 키는 읽지도 않는다 ④ 한 번에 최대 200행
-- ⑤ 출처별 1분 60번 (submit_rate 에 'dev:<출처 해시>' 로 기록, 출처를 모르면 전체 공용 240번).
-- p_code 는 [화면] 호환을 위해 받기만 하고 무시한다. 관리자 동작(지우기·상태 변경 등)은 그대로 운영자 코드가 필요하다.
-- 응답: { ok, now, max_log_id, max_cls_id, logs[], classifications[], severity[], cards[], status{backend_llm, loops{}, tokens_today{}} }
-- logs: id > p_since_log 오래된 것부터 최대 200건 (p_since_log=0 이면 가장 최근 200건). 다음 호출에 max_log_id 를 그대로 넘긴다.
-- classifications: 가장 최근 40건(최신 먼저, 지운 민원 제외). p_since_cls 는 받기만 한다 (상태가 바뀌므로 매번 40건).

-- 공개 응답에 나가는 글자를 가린다. core/devfeed.ts 의 redact() 와 같은 규칙 (환경 변수 값 자체를 지우는 것은 서버 쪽만 한다).
create or replace function dev_redact(p text)
returns text
language sql immutable as $$
  select regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
         regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
           p,
           '\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{8,}', '[해시]', 'g'),                                          -- bcrypt (운영자 코드 해시, 잘린 앞부분 포함)
           'eyJ[A-Za-z0-9_.-]{8,}', '[키]', 'g'),                                                           -- JWT (Supabase 키, 잘린 앞부분 포함)
           '(sk|sb|pk)[-_][A-Za-z0-9_-]{8,}', '[키]', 'g'),                                                 -- API 키 모양
           'postgres(ql)?://[^[:space:]"'']+', '[DB주소]', 'g'),
           '(https?://[^[:space:]"''?]+)\?[^[:space:]"'']*', '\1?[숨김]', 'g'),                               -- 주소의 ?뒤(serviceKey 등)
           '[A-Za-z]:\\+([^"''\\]+\\+)*[^"''\\]*', '[경로]', 'g'),                                            -- Windows 경로 (공백 포함)
           '/(Users|home)/[^[:space:]"'']*', '[경로]', 'g'),
           '[0-9]{6}[[:space:]]*[-–][[:space:]]*[1-4][0-9]{6}', '[주민번호]', 'g'),
           '([0-9]{4}[-[:space:]]?){3}[0-9]{4}', '[카드번호]', 'g'),
           '01[016-9][-.[:space:]]?[0-9]{3,4}[-.[:space:]]?[0-9]{4}', '[연락처]', 'g'),
           '0[0-9]{1,2}[-.[:space:]][0-9]{3,4}[-.[:space:]][0-9]{4}', '[연락처]', 'g'),
           '[[:alnum:]_.+-]+@[[:alnum:]_-]+\.[[:alnum:]_.]+', '[이메일]', 'g'),
           '[0-9]{2,3}[가-힣][[:space:]]?[0-9]{4}', '[차량번호]', 'g'),
           '\m[0-9]{1,3}(\.[0-9]{1,3}){3}\M', '[IP]', 'g'),
           '\m[0-9a-fA-F]{12,}\M', '[해시]', 'g')
$$;

create or replace function dev_feed(p_code text default null, p_since_log bigint default 0, p_since_cls bigint default 0)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_since bigint := greatest(coalesce(p_since_log, 0), 0);
  v_logs jsonb;
  v_max_log bigint;
  v_cls jsonb;
  v_sev jsonb;
  v_cards jsonb;
  v_loops jsonb;
  v_backend text;
  v_tok jsonb;
  v_today text := to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD');
  v_now text := to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS');
  v_src text := request_source();
  v_key text;
  v_limit integer;
begin
  -- 호출 빈도 제한 (submit_rate 재사용). 출처를 모르면 전체 공용 바구니.
  v_key := 'dev:' || coalesce(nullif(v_src, ''), 'all');
  v_limit := case when v_src = '' then 240 else 60 end;
  delete from submit_rate where src like 'dev:%'
     and at < to_char((now() at time zone 'Asia/Seoul') - interval '10 minutes', 'YYYY-MM-DD"T"HH24:MI:SS');
  if (select count(*) from submit_rate where src = v_key
        and at >= to_char((now() at time zone 'Asia/Seoul') - interval '60 seconds', 'YYYY-MM-DD"T"HH24:MI:SS')) >= v_limit then
    return jsonb_build_object('ok', false, 'error', '잠시 후 다시 보세요');
  end if;
  insert into submit_rate (src, at) values (v_key, v_now);

  select coalesce(jsonb_agg(to_jsonb(x) order by x.id), '[]'::jsonb), coalesce(max(x.id), v_since) into v_logs, v_max_log
    from (select y.id, y.created_at, y.agent, y.action,
                 dev_redact(y.input_summary) as input_summary, dev_redact(y.output_summary) as output_summary,
                 dev_redact(y.reasoning) as reasoning, y.latency_ms, y.tokens_in, y.tokens_out, y.tokens_cache
            from (select id, created_at, agent, action, input_summary, output_summary, reasoning, latency_ms,
                         coalesce(input_tokens, 0) as tokens_in, coalesce(output_tokens, 0) as tokens_out,
                         coalesce(cache_read_tokens, 0) as tokens_cache
                    from agent_log
                   where id > v_since
                   order by case when v_since > 0 then id end asc, id desc
                   limit 200) y) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.feedback_id desc), '[]'::jsonb) into v_cls
    from (select c.feedback_id, dev_redact(left(f.raw_text, 120)) as raw_text, c.label, c.status, c.is_safety, c.confidence,
                 dev_redact(c.agent_note) as agent_note, c.suggested_label, c.processed_at
            from classification c join feedback f on f.id = c.feedback_id
           where f.deleted_at is null
           order by c.feedback_id desc limit 40) x;

  select coalesce(jsonb_agg(jsonb_build_object(
           'label', s.label, 'window', s."window", 'as_of', s.as_of, 'freq', s.freq, 'avg_sentiment', s.avg_sentiment,
           'base_score', s.base_score, 'safety_w', s.safety_w, 'spike_w', s.spike_w, 'pending_w', s.pending_w,
           'score', s.score, 'grade', s.grade, 'formula', s.formula, 'spike_mult', s.spike_mult, 'safety_freq', s.safety_freq)
         order by s.score desc), '[]'::jsonb) into v_sev
    from severity s where s.as_of = (select max(as_of) from severity);

  select coalesce(jsonb_agg(jsonb_build_object(
           'issue_key', i.issue_key, 'label', i.label, 'zone_name', i.zone_name, 'grade', i.grade, 'is_safety', i.is_safety,
           'card_score', i.card_score, 'formula', i.formula, 'freq', i.freq, 'type_freq', i.type_freq,
           'text_source', i.text_source, 'fail_count', i.fail_count, 'grp', i.grp, 'rank_no', i.rank_no)
         order by i.rank_no), '[]'::jsonb) into v_cards
    from issue i where i.active = 1;

  select coalesce(jsonb_object_agg(w.name, jsonb_build_object('last_at', w.last_at, 'took_ms', w.took_ms, 'ok', w.ok, 'note', dev_redact(w.note))), '{}'::jsonb)
    into v_loops from worker_status w where w.name not like '\_%';
  select note into v_backend from worker_status where name = '_backend';

  select jsonb_build_object('input', coalesce(sum(input_tokens), 0), 'output', coalesce(sum(output_tokens), 0),
                            'cache', coalesce(sum(cache_read_tokens), 0))
    into v_tok from agent_log where created_at >= v_today;

  return jsonb_build_object(
    'ok', true, 'now', v_now,
    'max_log_id', v_max_log, 'max_cls_id', (select coalesce(max(feedback_id), 0) from classification),
    'logs', v_logs, 'classifications', v_cls, 'severity', v_sev, 'cards', v_cards,
    'status', jsonb_build_object('backend_llm', v_backend, 'loops', v_loops, 'tokens_today', v_tok));
end $$;

revoke all on function dev_redact(text) from public, anon, authenticated;
revoke all on function dev_feed(text, bigint, bigint) from public;
grant execute on function dev_feed(text, bigint, bigint) to anon, authenticated;

revoke all on function submit_feedback(bigint, text) from public;
revoke all on function admin_gate(text) from public, anon, authenticated;
revoke all on function request_source() from public, anon, authenticated;
revoke all on function check_admin(text) from public;
revoke all on function request_doc(text, text) from public;
revoke all on function set_action_status(bigint, text, text) from public;
revoke all on function delete_feedback(bigint, text) from public;
revoke all on function restore_feedback(bigint, text) from public;
revoke all on function list_deleted(text) from public;
revoke all on function resolve_review(bigint, text, boolean, text) from public;
revoke all on function dismiss_review(bigint, text) from public;
revoke all on function reopen_review(bigint, text) from public;
-- 방문객(anon)이 코드 없이 쓸 수 있는 것은 접수 하나뿐. 나머지는 실행은 열어 두되 코드가 맞아야 동작한다.
grant execute on function submit_feedback(bigint, text) to anon, authenticated;
grant execute on function check_admin(text) to anon, authenticated;
grant execute on function request_doc(text, text) to anon, authenticated;
grant execute on function set_action_status(bigint, text, text) to anon, authenticated;
grant execute on function delete_feedback(bigint, text) to anon, authenticated;
grant execute on function restore_feedback(bigint, text) to anon, authenticated;
grant execute on function list_deleted(text) to anon, authenticated;
grant execute on function resolve_review(bigint, text, boolean, text) to anon, authenticated;
grant execute on function dismiss_review(bigint, text) to anon, authenticated;
grant execute on function reopen_review(bigint, text) to anon, authenticated;

-- ── 운영자 설정 (D5-90) — 축제 이름·지역·기간, 구역(이름 변경·숨김), 유형별 담당 부서·연락처 ───────────────
-- 쓰기는 모두 admin_gate(운영자 코드). 검증 오류는 예외(raise)로 사용자 문구를 돌려준다 (코드 검사 결과는 반환값 {ok:false,error}).
-- 구역은 지우는 RPC 가 없다 (민원이 달려 있다) — 이름 변경·숨김만. 연락처는 숫자와 하이픈만(숫자 3~20개, 하이픈은 연달아 쓰지 않음).
-- 읽기 get_settings() 는 공개(코드 없음): 설정 화면이 쓴다. departments[].is_example = 기본 예시 번호(055-000-000x)인 동안 true.
create or replace function get_settings()
returns jsonb
language sql stable security definer set search_path = public, extensions as $$
  select jsonb_build_object(
    'festival', (select to_jsonb(f) - 'id' from (select name, region, start_date, end_date from festival order by id limit 1) f),
    'zones', coalesce((select jsonb_agg(jsonb_build_object('id', z.id, 'name', z.name, 'hidden', coalesce(z.hidden, 0),
               'feedback_count', (select count(*) from feedback f where f.zone_id = z.id and f.deleted_at is null)) order by z.id) from zone z), '[]'::jsonb),
    'departments', coalesce((select jsonb_agg(jsonb_build_object('label', d.label,
               'label_ko', case d.label when 'parking' then '주차/교통' when 'restroom' then '화장실' when 'price' then '가격/바가지'
                                        when 'guide' then '안내/동선' when 'crowd' then '혼잡' when 'safety' then '안전' else d.label end,
               'department', d.department, 'contact', d.contact, 'is_example', d.contact ~ '^055-000-000[0-9]$') order by d.label) from department_map d), '[]'::jsonb));
$$;

create or replace function save_festival(p_name text, p_region text, p_start_date text, p_end_date text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text; v_id bigint;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then return jsonb_build_object('ok', false, 'error', v_err); end if;
  if btrim(coalesce(p_name, '')) = '' then raise exception '축제 이름을 입력해 주세요'; end if;
  if btrim(coalesce(p_region, '')) = '' then raise exception '지역을 입력해 주세요'; end if;
  if length(btrim(p_name)) > 40 or length(btrim(p_region)) > 40 then raise exception '이름·지역은 40자 이내로 적어 주세요'; end if;
  if p_start_date !~ '^\d{4}-\d{2}-\d{2}$' or p_end_date !~ '^\d{4}-\d{2}-\d{2}$' then raise exception '기간은 YYYY-MM-DD 형식으로 적어 주세요'; end if;
  if p_end_date < p_start_date then raise exception '끝나는 날이 시작하는 날보다 빠를 수 없습니다'; end if;
  select id into v_id from festival order by id limit 1;
  if v_id is null then
    insert into festival (name, region, start_date, end_date) values (btrim(p_name), btrim(p_region), p_start_date, p_end_date);
  else
    update festival set name = btrim(p_name), region = btrim(p_region), start_date = p_start_date, end_date = p_end_date where id = v_id;
  end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function add_zone(p_name text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text; v_id bigint;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then return jsonb_build_object('ok', false, 'error', v_err); end if;
  if btrim(coalesce(p_name, '')) = '' then raise exception '구역 이름을 입력해 주세요'; end if;
  if length(btrim(p_name)) > 30 then raise exception '구역 이름은 30자 이내로 적어 주세요'; end if;
  if exists (select 1 from zone where name = btrim(p_name)) then raise exception '같은 이름의 구역이 이미 있습니다'; end if;
  insert into zone (festival_id, name) values ((select id from festival order by id limit 1), btrim(p_name)) returning id into v_id;
  return jsonb_build_object('ok', true, 'id', v_id);
end $$;

create or replace function rename_zone(p_id bigint, p_name text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then return jsonb_build_object('ok', false, 'error', v_err); end if;
  if not exists (select 1 from zone where id = p_id) then raise exception '없는 구역입니다'; end if;
  if btrim(coalesce(p_name, '')) = '' then raise exception '구역 이름을 입력해 주세요'; end if;
  if length(btrim(p_name)) > 30 then raise exception '구역 이름은 30자 이내로 적어 주세요'; end if;
  if exists (select 1 from zone where name = btrim(p_name) and id <> p_id) then raise exception '같은 이름의 구역이 이미 있습니다'; end if;
  update zone set name = btrim(p_name) where id = p_id;
  return jsonb_build_object('ok', true, 'id', p_id);
end $$;

create or replace function set_zone_hidden(p_id bigint, p_hidden boolean, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then return jsonb_build_object('ok', false, 'error', v_err); end if;
  if not exists (select 1 from zone where id = p_id) then raise exception '없는 구역입니다'; end if;
  update zone set hidden = case when p_hidden then 1 else 0 end where id = p_id;
  return jsonb_build_object('ok', true, 'id', p_id, 'hidden', case when p_hidden then 1 else 0 end);
end $$;

create or replace function save_department(p_label text, p_department text, p_contact text, p_code text)
returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare v_err text;
begin
  v_err := admin_gate(p_code);
  if v_err is not null then return jsonb_build_object('ok', false, 'error', v_err); end if;
  if not exists (select 1 from department_map where label = p_label) then raise exception '부서를 정할 수 없는 유형입니다: %', p_label; end if;
  if btrim(coalesce(p_department, '')) = '' then raise exception '담당 부서를 입력해 주세요'; end if;
  if length(btrim(p_department)) > 30 then raise exception '담당 부서는 30자 이내로 적어 주세요'; end if;
  if btrim(coalesce(p_contact, '')) !~ '^[0-9](-?[0-9]){2,19}$' then raise exception '연락처는 숫자와 하이픈만 써 주세요 (예: 055-123-4567)'; end if;
  update department_map set department = btrim(p_department), contact = btrim(p_contact) where label = p_label;
  return jsonb_build_object('ok', true);
end $$;

-- 마지막 갱신 시각 (D5-86): 공개 읽기, 시각만. 화면이 '몇 초 전 갱신'과 정체 경고에 쓴다.
-- agent_at = agent_log 의 가장 최근 동작, worker_at = worker_status 루프의 가장 최근 기록 ('_'로 시작하는 줄은 제외).
create or replace function get_freshness()
returns jsonb
language sql stable security definer set search_path = public, extensions as $$
  select jsonb_build_object(
    'server_now', to_char(now() at time zone 'Asia/Seoul', 'YYYY-MM-DD"T"HH24:MI:SS'),
    'severity_at', (select max(as_of) from severity),
    'agent_at', (select max(created_at) from agent_log),
    'worker_at', (select max(last_at) from worker_status where name not like '\_%'));
$$;

revoke all on function get_settings() from public;
revoke all on function get_freshness() from public;
revoke all on function save_festival(text, text, text, text, text) from public;
revoke all on function add_zone(text, text) from public;
revoke all on function rename_zone(bigint, text, text) from public;
revoke all on function set_zone_hidden(bigint, boolean, text) from public;
revoke all on function save_department(text, text, text, text) from public;
grant execute on function get_settings() to anon, authenticated;
grant execute on function get_freshness() to anon, authenticated;
grant execute on function save_festival(text, text, text, text, text) to anon, authenticated;
grant execute on function add_zone(text, text) to anon, authenticated;
grant execute on function rename_zone(bigint, text, text) to anon, authenticated;
grant execute on function set_zone_hidden(bigint, boolean, text) to anon, authenticated;
grant execute on function save_department(text, text, text, text) to anon, authenticated;

-- ── Realtime ───────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'feedback','classification','severity','alert','action_request','briefing','doc_job','issue']
  loop
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;

-- ── Storage: 조치요청서 DOCX ───────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('docs', 'docs', true)
on conflict (id) do nothing;
